version: "3.4"
services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./var/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: secure-database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    ports:
      - 8090:8080

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      driver: none
#    volumes:
#      - ./var/data/rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=whois-api
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
